version: 0.0
os: linux
files:
  - source: /index.html
    destination: /opt/bitnami/apache2/htdocs/
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root
